set-environment -g TMUX_PLUGIN_MANAGER_PATH "${XDG_DATA_HOME}/tmux/plugins/"

# Clone tmux plagin manager if it is missing
run "if [ ! -d "${XDG_DATA_HOME}/tmux/plugins/tpm" ]; then \
    git clone https://github.com/tmux-plugins/tpm ${XDG_DATA_HOME}/tmux/plugins/tpm \ 
fi"

# Something for color idk
set-option -sa terminal-overrides ",xterm*:Tc"

# Config reload
unbind r 
bind r source-file ${XDG_CONFIG_HOME}/tmux/tmux.conf

# Prefix key
unbind C-b
set -g prefix C-Space

set -g escape-time 0  # disable delays on escape sequences
set -g repeat-time 1000  # increase "prefix-free" window
set -g mouse on

set -g base-index 1 # Start windows and panes at 1, not 0
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on

# Splitting windows
unbind %
unbind \"
bind - split-window -v -c "#{pane_current_path}"
bind \\ split-window -h -c "#{pane_current_path}"

# Pane separators 
set -g pane-border-indicators arrows # [off | colour | arrows | both]
set -g pane-border-lines heavy # single, double, heavy, simple, number

# Navigating 
bind-key f resize-pane -Z
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin "tmux-plugins/tpm"
# set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

source-file ${XDG_CONFIG_HOME}/tmux/style.conf
# source-file ${XDG_CONFIG_HOME}/tmux/bindings.conf
# Initialize TMUX plugin manager 
run ${XDG_DATA_HOME}/tmux/plugins/tpm/tpm
